### ISSUE TITLE
setup confusion

### ISSUE THREAD

**Issue by GuidoS** [fraibacas/prefect-orion#3]
I think there is a step missing between this setup instruction below. I don't know what "create a flow run " means in this context. Were we supposed to open a webpage, if so which one.

```
* Deploy test flow and deployment
    ```
    make register-test-flow
    ```
    A flow named `my-docker-flow` and a `my-docker-flow/docker-example` deployment should have been created
* Create a flow run from the `Deployments` screen by selecting the deployment and clicking on `Run`

```

**Comment by fraibacas** [comment]
Hello!
The step before the first one you posted describes how to access the UI
`* Open http://prefect-server:4200 in your browser and verify Prefect UI is up and running`

The screenshot below shows how to run a flow from the deployment screen

`Create a flow run from the Deployments screen by selecting the deployment and clicking on Run`
![Uploading Screen Shot 2022-09-19 at 8.07.53 AM.png…]()

**Comment by fraibacas** [comment]
<img width="1648" alt="Screen Shot 2022-09-19 at 8 07 53 AM" src="https://user-images.githubusercontent.com/3450781/191034007-6a2abe67-083a-42bf-a00e-1766ce85ff06.png">

**Comment by GuidoS** [comment]
@fraibacas Thank you for your help on that.
